'use client';

import { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';
import { useScrollLock } from '@/hooks/useScrollLock';
import { formatCurrency } from '@/lib/utils';
import { RiCloseLine, RiMoneyDollarCircleLine, RiBankCardLine, RiQrCodeLine, RiWallet3Line } from 'react-icons/ri';
import api from '@/lib/api';
import toast from 'react-hot-toast';

const PAYMENT_METHODS = [
  { id: 'cash', label: 'Cash', icon: RiMoneyDollarCircleLine },
  { id: 'card', label: 'Card (POS)', icon: RiBankCardLine },
  { id: 'upi', label: 'UPI / QR', icon: RiQrCodeLine },
  { id: 'wallet', label: 'Wallet', icon: RiWallet3Line },
];

export default function CheckoutModal({ isOpen, onClose, onSuccess, cart, customer, appointmentId }) {
  const [mounted, setMounted] = useState(false);
  const [isClosing, setIsClosing] = useState(false);
  const [loading, setLoading] = useState(false);
  const [selectedMethods, setSelectedMethods] = useState(['cash']);
  const [amountReceived, setAmountReceived] = useState('');
  
  useScrollLock(isOpen);

  useEffect(() => {
    setMounted(true);
  }, []);

  const totalAmount = cart.reduce((sum, item) => sum + (item.cart_price * item.qty), 0);

  useEffect(() => {
    if (isOpen) {
      setAmountReceived(totalAmount.toString());
    }
  }, [isOpen, totalAmount]);

  if (!mounted || !isOpen) return null;

  const handleClose = () => {
    setIsClosing(true);
    setTimeout(() => {
      onClose();
      setIsClosing(false);
    }, 200);
  };

  const handlePayment = async () => {
    if (!customer) {
      toast.error('Customer is required');
      return;
    }

    const requestedAmount = parseFloat(amountReceived) || totalAmount;
    const isSplit = selectedMethods.includes('wallet') && requestedAmount > (customer?.wallet_balance || 0);
    const secondaryMethod = selectedMethods.find(m => m !== 'wallet');

    setLoading(true);
    try {
      // 1. Create Invoice
      const invoicePayload = {
        customer_id: customer.id,
        appointment_id: appointmentId ? parseInt(appointmentId) : undefined,
        items: cart.map(item => ({
          item_type: item.type ? (item.type.endsWith('s') && item.type !== 'services' ? item.type.slice(0, -1) : (item.type === 'services' ? 'service' : item.type)) : 'service',
          item_id: parseInt(item.id),
          quantity: parseInt(item.qty) || 1,
          unit_price: parseFloat(item.cart_price) || 0,
          staff_member_id: item.staff_member_id ? parseInt(item.staff_member_id) : undefined
        }))
      };

      const invoiceRes = await api.post('/invoices', invoicePayload);
      const invoiceId = invoiceRes.data?.id;

      if (!invoiceId) throw new Error('Failed to create invoice');

      // If user didn't change the amount, assume full payment including any taxes generated by backend
      const finalPaymentAmount = (parseFloat(amountReceived) === totalAmount) 
        ? parseFloat(invoiceRes.data.total_amount) 
        : (parseFloat(amountReceived) || totalAmount);

      let finalPaymentRes;

      if (isSplit) {
        const walletAmount = parseFloat(customer.wallet_balance || 0);
        if (walletAmount > 0) {
          await api.post(`/invoices/${invoiceId}/payment`, {
            amount: walletAmount,
            payment_method: 'wallet',
          });
        }
        
        const remainingAmount = parseFloat((finalPaymentAmount - walletAmount).toFixed(2));
        finalPaymentRes = await api.post(`/invoices/${invoiceId}/payment`, {
          amount: remainingAmount,
          payment_method: secondaryMethod,
        });
      } else {
        finalPaymentRes = await api.post(`/invoices/${invoiceId}/payment`, {
          amount: parseFloat(finalPaymentAmount),
          payment_method: selectedMethods[0],
        });
      }

      // If appointment exists, mark it as completed
      if (appointmentId) {
        await api.patch(`/appointments/${appointmentId}/status`, { status: 'completed' });
      }

      toast.success('Payment collected successfully!');
      
      // Close and pass invoice data for receipt
      handleClose();
      setTimeout(() => {
        onSuccess(invoiceRes.data, finalPaymentRes.data);
      }, 250);

    } catch (error) {
      console.error('Checkout error:', error);
      toast.error(error.response?.data?.message || 'Failed to process payment');
    } finally {
      setLoading(false);
    }
  };

  return createPortal(
    <div className={`fixed inset-0 z-[100] flex justify-end bg-black/60 backdrop-blur-sm ${isClosing ? 'animate-[fadeOut_0.2s_ease_forwards]' : 'animate-[fadeIn_0.2s_ease_forwards]'}`} onMouseDown={handleClose}>
      <div 
        className={`bg-admin-card text-admin-text w-full max-w-md h-full border-l border-admin-border shadow-2xl flex flex-col ${isClosing ? 'animate-[slideOutRight_0.2s_ease_forwards]' : 'animate-[slideInRight_0.3s_ease_forwards]'}`}
        onMouseDown={e => e.stopPropagation()}
      >
        <div className="flex items-center justify-between px-6 py-5 border-b border-admin-border bg-admin-surface/50 shrink-0">
          <h2 className="text-xl font-bold">Collect Payment</h2>
          <button onClick={handleClose} className="text-admin-text-secondary hover:text-admin-text p-2 rounded-md hover:bg-admin-surface-light transition-colors">
            <RiCloseLine className="text-2xl" />
          </button>
        </div>

        <div className="overflow-y-auto custom-scrollbar flex-1 p-6 space-y-6">
          {/* Summary */}
          <div className="bg-brand/10 border border-brand/20 rounded-xl p-6 text-center">
            <p className="text-sm font-semibold text-brand mb-1">Total Amount Due</p>
            <p className="text-4xl font-black text-brand">{formatCurrency(totalAmount)}</p>
            {customer && (
              <p className="text-sm text-admin-text-secondary mt-2">
                Billed to: <span className="font-bold text-admin-text">{customer.first_name} {customer.last_name}</span>
              </p>
            )}
          </div>

          {/* Payment Methods */}
          <div>
            <h3 className="text-sm font-bold uppercase text-admin-text-secondary mb-3">Payment Method</h3>
            <div className="grid grid-cols-2 gap-3">
              {PAYMENT_METHODS.map(method => {
                const Icon = method.icon;
                const isSelected = selectedMethods.includes(method.id);
                const isDisabled = method.id === 'wallet' && (!customer || (customer.wallet_balance || 0) <= 0);
                return (
                  <button
                    key={method.id}
                    disabled={isDisabled}
                    onClick={() => {
                      const requestedAmount = parseFloat(amountReceived) || totalAmount;
                      const isWalletInsufficient = requestedAmount > (customer?.wallet_balance || 0);

                      if (method.id === 'wallet') {
                        if (isSelected) {
                          setSelectedMethods(selectedMethods.filter(m => m !== 'wallet'));
                        } else {
                          if (isWalletInsufficient) {
                            if (selectedMethods.length === 1 && selectedMethods[0] !== 'wallet') {
                              setSelectedMethods(['wallet', selectedMethods[0]]);
                            } else {
                              setSelectedMethods(['wallet']);
                            }
                          } else {
                            setSelectedMethods(['wallet']);
                          }
                        }
                      } else {
                        if (selectedMethods.includes('wallet') && isWalletInsufficient) {
                          setSelectedMethods(['wallet', method.id]);
                        } else {
                          setSelectedMethods([method.id]);
                        }
                      }
                    }}
                    className={`flex flex-col items-center justify-center gap-2 p-4 rounded-xl border-2 transition-all ${
                      isDisabled
                        ? 'border-admin-border bg-admin-surface/30 text-admin-text-secondary/30 cursor-not-allowed opacity-50'
                        : isSelected 
                          ? 'border-brand bg-brand/5 text-brand shadow-md shadow-brand/10' 
                          : 'border-admin-border bg-admin-surface text-admin-text-secondary hover:border-admin-text-muted hover:text-admin-text'
                    }`}
                  >
                    <Icon className="text-2xl" />
                    <span className="text-sm font-bold text-center">
                      {method.label}
                      {method.id === 'wallet' && customer && (
                        <span className="block text-[10px] font-normal opacity-80 mt-0.5 whitespace-nowrap">
                          {formatCurrency(customer.wallet_balance || 0)}
                        </span>
                      )}
                    </span>
                  </button>
                );
              })}
            </div>
            
            {/* Split warning directly below grid */}
            {selectedMethods.includes('wallet') && customer && (parseFloat(amountReceived) || totalAmount) > (customer.wallet_balance || 0) && (
               <p className="text-sm font-semibold text-orange-500 mt-3 text-center">
                 Wallet balance ({formatCurrency(customer.wallet_balance || 0)}) is insufficient. Please select a secondary method for the remaining {formatCurrency((parseFloat(amountReceived) || totalAmount) - (customer.wallet_balance || 0))}.
               </p>
            )}
          </div>

          {/* Amount Received (for partial/extra) */}
          <div>
            <h3 className="text-sm font-bold uppercase text-admin-text-secondary mb-3">Amount Received</h3>
            <div className="relative">
              <span className="absolute left-4 top-1/2 -translate-y-1/2 text-admin-text-secondary font-bold">₹</span>
              <input
                type="number"
                value={amountReceived}
                onChange={(e) => setAmountReceived(e.target.value)}
                className="w-full bg-admin-surface border-2 border-admin-border rounded-xl py-3 pl-8 pr-4 font-bold text-lg focus:outline-none focus:border-brand transition-colors"
                placeholder="0.00"
              />
            </div>
          </div>

          {/* Split Payment Options if Wallet is insufficient */}
          {/* Removed as we now select secondary method from the main grid */}
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-admin-border bg-admin-surface/50 shrink-0">
          <button 
            type="button"
            disabled={
              loading || 
              selectedMethods.length === 0 || 
              (selectedMethods.includes('wallet') && (parseFloat(amountReceived) || totalAmount) > (customer?.wallet_balance || 0) && selectedMethods.length < 2)
            }
            onClick={handlePayment}
            className="w-full py-4 rounded-xl font-bold bg-brand text-white hover:bg-brand-dark transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-xl shadow-brand/20 active:scale-[0.98]"
          >
            {loading ? 'Processing...' : `Collect ${formatCurrency(parseFloat(amountReceived) || totalAmount)}`}
          </button>
        </div>
      </div>
    </div>,
    document.body
  );
}
